(()=>{
 const previous=window.adminView||adminView;
 async function call(action,payload={}){const {data,error}=await sb.functions.invoke('manage-staff',{body:{action,...payload}});if(error)throw error;if(data?.error)throw new Error(data.error);return data}
 async function render(me){if(!['owner','admin'].includes(me.role))return previous('diary',me);const el=document.querySelector('#admin');el.innerHTML='<div class="admin-hero"><div><span class="eyebrow">Team management</span><h1>Barbers & staff logins</h1><p>Add barbers, edit their details and manage access to the staff dashboard.</p></div></div><section class="dash-section"><div id="staffManage"><p>Loading team…</p></div></section>';try{const data=await call('list'),rows=data.barbers||[];document.querySelector('#staffManage').innerHTML=`<form id="newBarber" class="formgrid"><label class="field">Name<input name="name" required placeholder="Barber name"></label><label class="field">Title<input name="title" value="Barber"></label><label class="field">Staff login email<input type="email" name="email" placeholder="Optional"></label><label class="field">Temporary password<input type="password" name="password" minlength="8" placeholder="8+ characters"></label><button class="btn field full">Add barber</button><p class="field full" id="staffMsg"></p></form><div class="review-admin-list" style="margin-top:24px">${rows.map(b=>`<article class="customer-card" data-barber="${b.id}"><div class="section-head"><div><h3>${esc(b.name)}</h3><p>${esc(b.title||'Barber')} · ${b.active?'Active':'Inactive'}</p></div><span class="pill">${b.staff?.role==='owner'?'Owner':b.staff?.email?'Login active':'No login'}</span></div><div class="formgrid"><label class="field">Name<input class="staff-name" value="${esc(b.name)}"></label><label class="field">Title<input class="staff-title" value="${esc(b.title||'Barber')}"></label><label class="field">Login email<input class="staff-email" type="email" value="${esc(b.staff?.email||'')}"></label><label class="field">New password<input class="staff-pass" type="password" minlength="8" placeholder="Leave blank to keep current"></label></div><div class="modal-actions" style="margin-top:12px"><button class="btn staff-save">Save changes</button>${!b.staff?'<button class="btn ghost staff-login">Create staff login</button>':''}${b.staff?.role!=='owner'?'<button class="btn ghost staff-remove">Remove barber</button>':''}</div></article>`).join('')}</div>`;
 const msg=document.querySelector('#staffMsg');document.querySelector('#newBarber').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target);msg.textContent='Adding…';try{await call('create',{name:f.get('name'),title:f.get('title'),email:f.get('email'),password:f.get('password')});await render(me)}catch(x){msg.textContent=x.message}}
 document.querySelectorAll('[data-barber]').forEach(card=>{const id=card.dataset.barber,name=()=>card.querySelector('.staff-name').value.trim(),title=()=>card.querySelector('.staff-title').value.trim(),email=()=>card.querySelector('.staff-email').value.trim(),password=()=>card.querySelector('.staff-pass').value;card.querySelector('.staff-save').onclick=async()=>{try{await call('update',{barber_id:id,name:name(),title:title(),email:email(),password:password(),active:true});await render(me)}catch(x){alert(x.message)}};card.querySelector('.staff-login')?.addEventListener('click',async()=>{try{await call('create_login',{barber_id:id,email:email(),password:password()});await render(me)}catch(x){alert(x.message)}});card.querySelector('.staff-remove')?.addEventListener('click',async()=>{if(!confirm(`Remove ${name()} from active barbers and revoke their staff login? Existing booking history will be kept.`))return;try{await call('remove',{barber_id:id});await render(me)}catch(x){alert(x.message)}})})
 }catch(e){document.querySelector('#staffManage').innerHTML=`<p class="error">${esc(e.message)}</p>`}}
 }
 window.adminView=adminView=async function(v,me){if(v==='staff')return render(me);return previous(v,me)};
})();